sudo: required
language: python
python:
  - "3.6.4"
  - "3.7"
  - "3.8"
  - "3.8-dev"  # 3.8 development branch
services:
  - docker
before_install:
  - pip install -U docker-compose 
script: 
  - make bootstrap
  - make test
